### ISSUE TITLE
SwiftUI with UIKit issue

### ISSUE THREAD

**Issue by raspberry-hu** [WalletConnect-Labs/WalletConnectSwiftV2#136]
I'm coding with SwiftUI. I choose to use WalletConnectSwiftV2 library but looks like it was written in UIKit. How can i use this library in SwiftUI?

**Comment by MisterVants** [comment]
Actually, the implementation of WalletConnect on Swift is agnostic of UI frameworks, you can consume the library from any app written in UIKit or SwiftUI without distinction.

The only use of UIKit that we make is on our example app (which we will be updating as we improve the framework) to show basic usage of the SDK, which has nothing to do with the SDK implementation itself.
