### ISSUE TITLE
Rename Repository and Swift Package

### ISSUE THREAD

**Issue by MisterVants** [WalletConnect-Labs/WalletConnectSwiftV2#2]
As discussed, let's start clean and name the project accordingly. 

My name suggestion is: 
- Rename the repository as WalletConnectSwiftV2 (anyone have a better suggestion?)
- Rename the package as WalletConnect, so that is can be imported in Swift code simply with `import WalletConnect`

V1 is exported as `WalletConnectSwift`, so namespaces won't conflict if both need to be imported in a single file.

**Comment by chadyj** [comment]
Sounds like a plan.

Sound good @pedrouid @llbartekll?

**Comment by pedrouid** [comment]
My OCD brain says "highest priority" on this 😂  I'm fully onboard on this

**Comment by BartekBright** [comment]
Sounds good :)

**Comment by llbartekll** [comment]
Sounds Good :)

**Comment by chadyj** [comment]
I updated the repo name to `WalletConnectSwiftV2`.

@MisterVants We have consensus to rename the package.
