### ISSUE TITLE
App crashes when creating websocket task

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect-Labs/WalletConnectSwiftV2#44]
When I build and run app with WalletConnect package app crashes with exception:

> Terminating app due to uncaught exception 'NSGenericException', reason: 'WebSocket tasks can only be created with ws or wss schemes'

**Comment by llbartekll** [comment]
@MisterVants could you take a look at this?

**Comment by MisterVants** [comment]
Sure, by the description it seems a simple error: the web socket was opened with a URL that didn't have a `ws` or `wss` scheme. When it did happen, were you passing a valid web socket URL?

If it was a correct URL, this might be a weird error.

**Comment by llbartekll** [comment]
@MisterVants  I cannot reproduce it, maybe I had a typo in url, sorry for bothering you then.
