### ISSUE TITLE
Pairing integration test - happy flow

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect-Labs/WalletConnectSwiftV2#54]
Two swift client instances Proposer(P) and Responder(R) should be able to establish pairing with each other over staging server.
Swift Client should be able to:
- [x] (P) propose pairing and expose proposal uri
- [x]  (R) settle pairing and respond on acknowledgement
- [x]  (P) settle pairing on response from (R)
- [x] Integration test target needs to be merged #25

**Comment by llbartekll** [comment]
@MisterVants could you merge integration test target #25 even without relay <-> relay tests?

**Comment by MisterVants** [comment]
Sure, should I'll leave the test commented to avoid failing on the CI for now

**Comment by llbartekll** [comment]
thank you. Commented test is not a problem to me, we have a task to resolve the issue so it will not stay commented forever.
