### ISSUE TITLE
Expose client interface

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect-Labs/WalletConnectSwiftV2#73]
Client should expose following methods for app:

- [x] pair() - for responder to receive a session proposal from a proposer
- [x] reject() - for responder to reject a session proposal 
- [x] approve() - for responder to approve a session proposal
- [x] disconnect() - for either to disconnect a session
- [x] connect() -> String? - for proposer to propose a session to a responder, returns pairing uri if initiating new pairing
- [x] respond() - for responder to respond JSON-RPC
- [x] request() - for proposer to request JSON-RPC
- [x] getActiveSessions()
- [x] getActivePairings() - for proposer to propose new sessions over active pairings

WalletConnectClientDelegate methods:

- [x]   didReceiveSessionProposal(_ sessionProposal: SessionType.Proposal)
- [x]   didSettleSession(_ sessionSettled: SessionType.Settled)
- [x]  didSettlePairing(_ settledPairing: PairingType.Settled)

**Comment by llbartekll** [comment]
@MisterVants if you need more methods from the client to accomplish the milestone, feel free to add them to the task description and I will provide the implementation.

**Comment by MisterVants** [comment]
We are already doing it organically on other tasks. We'll find more places to change when updating the example app again.
